stages:
  - build

before_script:
  - git submodule init
  - git submodule update
  # For lack of access to anaconda from PAN
  - . /home/Alistair.Adcroft/bin/anaconda3/bin/activate py3

# Test
build:
  stage: build
  tags:
    - pan
  script:
    # Fetched some files from archive which are unobtainable through the firewall
    - cp -n /archive/gold/datasets/obs/SeaWiFS/fill_ocean_color/seawifs-clim-1997-2010.nc  .
    # Make everything
    - make
